name: Publish to NPM

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish to NPM
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Setup node version
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build

      - name: Authenticate
        run: echo ${{ secrets.NPM_TOKEN }} > .npmrc

      - name: Publish
        run: yarn publish
